# Dockerfile с поддержкой SSL
FROM nginx:alpine

# Копируем готовую сборку из локальной папки build
COPY build /usr/share/nginx/html

# Копируем конфигурацию nginx с SSL
COPY nginx-ssl.conf /etc/nginx/conf.d/default.conf

# Открываем порты 80 и 443
EXPOSE 80 443

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
